![imagen](./img/ejercicios.png)

## Ejercicio 1
1. Crea un array que vaya del 0 al 9 y que se llame `my_array`
2. Imprime por pantalla los elementos [9 7 5 3 1] en ese orden.

In [28]:
import numpy as np

In [29]:
from audioop import reverse


my_array = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
res = my_array [::-1]
res[np.where(res % 2 != 0)] 

array([9, 7, 5, 3, 1])

In [30]:
# Parte 1

my_array = np.arange(10)
print(my_array)

# Parte 2

print(my_array[::-2]) # muestra desde el final hasta el principio con saltos de 2. Se pone -2 porque empieza desde el final que es -1. Así conseguimos sacar la secuencia que nos pide ivertida y con saltos de 2 en 2

[0 1 2 3 4 5 6 7 8 9]
[9 7 5 3 1]


## Ejercicio 2
Imprime por pantalla la secuencia [8 7] del array `my_array`

In [31]:
print(my_array)
print(my_array[-2:-4:-1])

[0 1 2 3 4 5 6 7 8 9]
[8 7]


In [32]:
# Otra forma

print(my_array[8:6:-1])


[8 7]


## Ejercicio 3
Imprime por pantalla la secuencia [2 1 0] de `my_array`

In [33]:
# Tres maneras diferentes 

print(my_array)
print(my_array[-8::-1]) # Mostrar de la posición/índice -8 (2) hasta el final, índice -1 (0)
print(my_array[2::-1])
print(my_array[0:3][::-1])

[0 1 2 3 4 5 6 7 8 9]
[2 1 0]
[2 1 0]
[2 1 0]


In [34]:
# Otra solución en dos pasos

array1 = my_array[0:3] # Hacemos la secuencia en el orden natural
array2 = array1[::-1] # Ivertimos la secuencia del paso anterior en un array nuevo
print(array1)
print(array2)

[0 1 2]
[2 1 0]


## Ejercicio 4
1. Crea una matriz de 4x5, con una secuencia del 1 al 20
2. Invierte totalmente la matriz. Tanto las filas, como las columnas

In [35]:
my_matrix = np.arange(1, 21).reshape((4,5)) # (1, 21) nos indica la secuencia de numeros de la matriz, ((4,5)) nos indica que tiene 4 columnas y 5 filas
print(my_matrix)

print(np.flip(my_matrix)) # Función que nos invierte la matriz entera de forma simple

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
[[20 19 18 17 16]
 [15 14 13 12 11]
 [10  9  8  7  6]
 [ 5  4  3  2  1]]


In [36]:
# Otra manera

print(my_matrix[::-1, ::-1]) # Aqui le pedimos que nos ivierta en dos pasos todas las filas primero y todas las columnas

[[20 19 18 17 16]
 [15 14 13 12 11]
 [10  9  8  7  6]
 [ 5  4  3  2  1]]


## Ejercicio 5

Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[1, 2],
       [6, 7]])
```

In [37]:
my_matrix = np.arange(1, 21).reshape((4,5))
print(my_matrix)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [96]:
my_matrix[::0]

ValueError: slice step cannot be zero

## Ejercicio 6
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[ 1,  3,  5],
       [11, 13, 15]])
```

In [38]:
my_matrix[::2, ::2]


array([[ 1,  3,  5],
       [11, 13, 15]])

## Ejercicio 7
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[ 5,  4,  3,  2,  1],
       [10,  9,  8,  7,  6],
       [15, 14, 13, 12, 11]])
```

In [97]:
print(my_matrix[:-1, ::-1])

[[ 5  4  3  2  1]
 [10  9  8  7  6]
 [15 14 13 12 11]]


## Ejercicio 8
Dado el siguiente array:

```Python
x = np.array(["Loro", "Perro", "Gato", "Loro", "Perro"])
```

Filtra el array para quedarte únicamente con los loros.

Resuélvelo de dos maneras diferentes

In [98]:
x = np.array(["Loro", "Perro", "Gato", "Loro", "Perro"])

# Máscara de Booleanos

mask = np.array([True, False, False, True, False])

x[mask]

array(['Loro', 'Loro'], dtype='<U5')

In [100]:
# Método 2

mask = x == "Loro"
print(mask)
x[mask]

[ True False False  True False]


array(['Loro', 'Loro'], dtype='<U5')

In [101]:
# Método 3

mask = np.where(x == "Loro")
print(mask)
x[mask]

(array([0, 3]),)


array(['Loro', 'Loro'], dtype='<U5')

## Ejercicio 9
Crea una secuencia de 20 elementos y transformala en un array compuesto por 2 matrices de 5x2

In [108]:

my_matrix2 = np.arange(1, 21).reshape((2,5,2)) # reshape((2,5,2)) = 2 dimensiones, 5 filas, 2 columnas
print(my_matrix2)

[[[ 1  2]
  [ 3  4]
  [ 5  6]
  [ 7  8]
  [ 9 10]]

 [[11 12]
  [13 14]
  [15 16]
  [17 18]
  [19 20]]]


## Ejercicio 10
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[20, 19, 18, 17, 16],
       [15, 14, 13, 12, 11],
       [10,  9,  8,  7,  6],
       [ 5,  4,  3,  2,  1]])
```

In [111]:
my_matrix3 = np.flip(my_matrix)
my_matrix3

array([[20, 19, 18, 17, 16],
       [15, 14, 13, 12, 11],
       [10,  9,  8,  7,  6],
       [ 5,  4,  3,  2,  1]])

## Ejercicio 11
Crea un array de 10 0s. ¿Cuánto ocupa en memoria?

Sustituye el 4to elemento por 1, e imprime el array por pantalla

In [120]:
array_100 = np.full((4), 100)
print(array_100)

array_100[3] = 1
print(array_100)

print(x.size) # Tenemos 5 elementos en el array de 100s
 
print(x.itemsize) # Cada elemento del array de 100s ocupa 20 bytes de memoria
 
print(x.size * x.itemsize) # si multiplicamos cada elemento por lo que ocupa cda uno de ellos

[100 100 100 100]
[100 100 100   1]
5
20
100


## Ejercicio 12
Crea un vector que vaya del 10 al 49

Inviértelo

In [128]:
vector1 = np.arange(10, 50)
print(vector1)

vector1[::-1]
print(vector1[::-1])

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


## Ejericio 13
Encuentra los indices de los valores que no sean 0 del siguiente vector [1,2,0,0,4,0]. El output sería [0, 1, 4]. [Encuentra el método apropiado en la documentación.](https://numpy.org/doc/)

In [141]:
vector2 = np.array([1,2,0,0,4,0])

non_0 = np.nonzero(vector2)

print(non_0)




(array([0, 1, 4]),)


## Ejercicio 14
Crea una matriz de numeros aleatorios 10x10. Encuentra los valores mínimo y máximo.

In [147]:
matrix_ran = (np.random.randint(50, size = (10,10)))

print(matrix_ran)

np.min(matrix_ran), np.max(matrix_ran)

[[22 11 15 46  0 21 13 14 45 24]
 [ 6 21 34  1 37 38  7 47  8 12]
 [47 48 26 46 15  0 44 45 30 30]
 [47  8 18 37 19  7  4 46 33 44]
 [ 6 22 16  6  4  0 23  2 14 39]
 [24 29  3  6 25 44  6 22 19 25]
 [31 24 43  9 28 15  3 15  2 16]
 [22 39  7 14 36  0 11 49  3 48]
 [19 37 39  1 22 35 27 49 34 42]
 [14 27 14 27 15 27  1 27 17 26]]


(0, 49)

## Ejercicio 15
Crea un vector aleatorio de tamaño 30 y calcula su media

In [152]:
vector_ran = (np.random.randint(50, size = (30)))
print(vector_ran)

np.mean(vector_ran)

[30 18 49 41 34 25 47 21 32 25 38 29 36 14 10  6  3 26 47 30 39 40 20 18
 26 11  6 48 15 47]


27.7

## Ejercicio 16
Crea un array cuadrado de 2D, con las dimensiones que quiras, pero que todo el borde esté compuesto por 1s, y el interior por 0s

In [159]:
mi_cuadrado = np.ones((10,10))
print(mi_cuadrado)

mi_cuadrado[1:-1, 1:-1] = 0

print("\n")

print(mi_cuadrado)


[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


## Ejercicio 17
Crea una mtriz de 8x8, y rellénala con 0s y 1s. Tienes que replicar:
```Python
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
```

In [184]:
mi_matrix4 = np.zeros((8, 8), dtype=int)
mi_matrix4[1::2, ::2] = 1
mi_matrix4[::2, 1::2] = 1

print(mi_matrix4)
             

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


## Ejercicio 18
Replica la matriz del apartado anterior, pero en este caso usando [la función `tile`](https://numpy.org/doc/stable/reference/generated/numpy.tile.html)

In [212]:
a = np.array([0, 1, 0, 1])
b = np.array([1, 0, 1, 0])

mar_1 = np.tile(a, 2)
mar_2 = np.tile(b, 2)



np.vstack([mar_1, mar_2])


array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

## Ejercicio 9
Crea una matriz aleatoria de 5x5 y normaliza sus valores. Para normalizar tienes que restar sus valores por la media(`np.mean`) y dividir el resultado por la desviación estándar(`np.std`).

## Ejercicio 10
1. Crea una secuencia de números que vayan del 0 al 10.
2. Crea un nuevo array, que parta del anterior, pero sustituya todos los elementos entre el 3 y el 8, por el valor -1
3. Crea un nuevo array que niegue todos los elementos entre el 3 y el 8

## Ejercicio 11
#### Bonus track. Mini hundir la flota
1. Crea un tablero de 10x10 relleno del carácter espacio ( ).
2. Posiciona un par de barcos en [(0,1), (1,1)] y [(1,3), (1,4), (1,5), (1,6)]. Los barcos serán Os mayúsculas. Como ves, un barco de dos posiciones de eslora y otro de cuatro.
3. Recibe un disparo en uno de los barcos, sustituyendo la O por una X
4. Recibe un disparo en agua, sustituyendo uno de los espacios por un guión: -
5. Ignorando los disparos recibidos, ahora prueba a posicionar otro barco de 4 posiciones dentro del tablero, pero **de manera ALEATORIA.**

**TIP apartado 5**: El barco tendrá una posición inicial aleatoria dentro del tablero, y una orientación también aleatoria (N,S,E,O).

Por ejemplo, si tu posicion inicial fuese (5,0) y la orientación O, no podrias ponerlo porque se sale del tablero. Ahora bien, si fuese orientación este, si podrías, y ocuparía las posiciones [(5,0), (5,1), (5,2), (5,3)]. Por tanto tendrás que iterar con un bucle si es posible encajar el barco en el tablero, y el bucle terminará cuando lo consigas encajar. **Ojo con las posiciones donde ya hay barco!!!**

Usa `import random` para elegir las coordenadas aleatorias.

In [175]:
import numpy as np
from numpy import reshape

mini_hun_flo = np.__str__("Loro", "Loro")((5,2))
print(mini_hun_flo)

TypeError: expected 0 arguments, got 2